version: '3.8'

services:
  solr:
    image: solr:8.11.2
    container_name: solr
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/var/solr
    command: >
      bash -c "
        solr-precreate australia3 &&
        /opt/docker-solr/scripts/wait-for-solr.sh
      "
    networks:
      - search-network

  flask-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-api
    ports:
      - "5000:5000"
      - "5678:5678"  # Debugpy port
    volumes:
      - .:/app        # Map your entire project for live-reload + VS Code access
    working_dir: /app
    environment:
      - FLASK_APP=flask_app.py
      - FLASK_ENV=development
    command: >
      flask run --host=0.0.0.0 --reload
    networks:
      - search-network
    depends_on:
      - solr

volumes:
  solr_data:

networks:
  search-network:
    name: search-network
