version: '3.8'

services:
  solr:
    image: solr:8.11.2
    container_name: solr
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/var/solr
      - ./schema.json:/schema.json
      - ./solr_docs.json:/solr_docs.json  # Pre-generated outside Docker!
    command: >
      bash -c "
        solr-precreate australia &&
        /opt/docker-solr/scripts/wait-for-solr.sh &&
        until curl -s http://localhost:8983/solr/australia/schema -X POST -H 'Content-type:application/json' --data-binary @/schema.json; do sleep 5; done &&
        curl -X POST -H 'Content-Type: application/json' 'http://localhost:8983/solr/australia/update?commit=true' --data-binary @/solr_docs.json
      "
    networks:
      - search-network

  flask-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-api
    ports:
      - "5000:5000"
      - "5678:5678"  # Debugpy port
    volumes:
      - .:/app        # Map your entire project for live-reload + VS Code access
    working_dir: /app
    environment:
      - FLASK_APP=flask_app.py
      - FLASK_ENV=development
    command: >
      flask run --host=0.0.0.0
    networks:
      - search-network
    depends_on:
      - solr

volumes:
  solr_data:

networks:
  search-network:
    name: search-network
